repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '(\\.venv|site-packages|\\.mypy_cache|__pycache__)'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--explicit-package-bases]
        pass_filenames: false
        exclude: '(\\.venv|site-packages|\\.mypy_cache|__pycache__)'
